IMAGE = "centos/7"
NODES = 2

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = IMAGE
    subconfig.vm.hostname = "master"
    subconfig.vm.network :private_network, ip: "10.0.0.10"
  end
  
  (1..NODES).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    systemctl stop firewalld; systemctl disable firewalld; swapoff -a
  SHELL
end
